### ISSUE TITLE
Can't load the package in google colab

### ISSUE THREAD

**Issue by seuriously** [davemlz/spyndex#11]
Hi, thank you for developing the package.
I tried to use it in fresh google colab session but it keeps giving me dask error.

The installation is successful but loading the package gives me this error:
![image](https://user-images.githubusercontent.com/7880604/151766004-7df497d6-01ed-4fa6-be4b-43f969e8c7b8.png)

thank you..

**Comment by davemlz** [comment]
Hi, @seuriously!

I'm aware of this. Colab is having some trouble with the way it is loading python packages. In your local machine it should work, but to make it work in Colab, please install pyyaml==5.4.1:

```python
!pip install spyndex pyyaml==5.4.1

import spyndex
```

Let me know if it works!

Best,

Dave

**Comment by seuriously** [comment]
yes.. it can load now..
thank you for your quick solution!!
