### ISSUE TITLE
issue in calculating some of the vegetation indices 

### ISSUE THREAD

**Issue by Raziehgithub** [davemlz/spyndex#4]
Hi, 
I have used this library to calculate some vegetation indices, but the "EVI", "GBNDVI", "GLI", "GRNDVI", "MSAVI", "MTVI2", and "VARI" could not calculate and I got this error:
MergeError: conflicting values for variable 'band' on objects to be combined. You can skip this check by specifying compat='override'.

**Comment by davemlz** [comment]
Hi, @Raziehgithub!

I wasn't able to reproduce the error you got. Could you please share the code here?

**Comment by julianblue** [comment]
@davemlz I believe this has to do with some returned indices not having the same coordinates. Problematic coordinates seem to be "gsd", "common_name", "band" and some others. As of my understanding XR.concat should avoid this issue with the compat= "no_conflicts" statement, which is default. Might adding a coordinate check help to ensure all calculated indices contain the same coordinates ?

**Comment by davemlz** [comment]
Yes. You're totally right, @julianblue! I'm on it and I hope to have it done later :) For now and until then, [@Raziehgithub, @julianblue], if you want, a workaround for this problem is to set `returnOrigin=False`. With this the indices are not concatenated and are returned as a list :)

**Comment by davemlz** [comment]
The problem was solved! If you download the dev version it should work now :) `pip install git+https://github.com/davemlz/spyndex`.

Thank you for pointing this out!

**Comment by Raziehgithub** [comment]
Thank you for your response and sharing your useful github!
